# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest

    steps:
      # Check-out repository
      - uses: Nuitka/Nuitka-Action@v0.4

      # Build python script into a stand-alone exe
      - uses: Nuitka/Nuitka-Action@v0.4
        with:
          script-name: small_projects/Calculator/calc.py
      
      # Uploads artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: exe
          path: build/calculator.exe
